
###registration
POST http://localhost:8081/auth/registration
Content-Type: application/json

{
  "name": "Yorqin",
  "surname": "Mislimov",
  "email": "princename6363@gmail.com",
  "phone": "+998919916363",
  "password": "12345678"
}


###login
POST http://localhost:8081/auth/login
Content-Type: application/json

{
"email": "alisherodilov482@gmail.com",
"password": "1999"
}