
###registration
POST http://localhost:8081/auth/registration
Content-Type: application/json

{
  "name": "Qurbonali",
  "surname": "Qulmatov",
  "email": "allidele574@gmail.com",
  "phone": "+9989725541497",
  "password": "12345678"
}


###login
POST http://localhost:8081/auth/login
Content-Type: application/json

{
"email": "alisherodilov482@gmail.com",
"password": "1999"
}